apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-home-app
  labels:
    app: garden-home-app
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.deploymentStrategyType | default "Recreate" }}
  selector:
    matchLabels:
      app: garden-home-app
  template:
    metadata:
      labels:
        app: garden-home-app
        app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    spec:
      containers:
        - name: garden-home-app
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.env }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources: {{- toYaml .Values.resources | nindent 12 }}
