apiVersion: apps/v1
kind: Deployment
metadata:
  name: garden-home-api
  labels:
    app: garden-home-api
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.deploymentStrategyType | default "Recreate" }}
  selector:
    matchLabels:
      app: garden-home-api
  template:
    metadata:
      labels:
        app: garden-home-api
        app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    spec:
      containers:
        - name: garden-home-api
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.env }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.secretRef }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretRef }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /app/dist/api/data
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: garden-home-api-data
      {{- end }}
