import type { AppRegistryOverride } from "./app-types.js";

export const appRegistryOverrides: AppRegistryOverride[] = [
  { id: "employee", sourcePath: "/home/ubuntu/Projects/hr-platform/apps/employee-web" },
  { id: "lista-plac", sourcePath: "/home/ubuntu/Projects/hr-platform/apps/lista-plac-web" },
  { id: "personnel-notes", sourcePath: "/home/ubuntu/Projects/personnel-notes-app" },
  { id: "rekrutacja", sourcePath: "/home/ubuntu/Projects/rekrutacja/rekrutacja-app" },
  { id: "system-rezerwacji", sourcePath: "/home/ubuntu/Projects/beo/app" },
  { id: "rezerwacje-oaza", sourcePath: "/home/ubuntu/Projects/rezerwacje-oaza/app" },
  { id: "rezerwacje-restauracja", sourcePath: "/home/ubuntu/Projects/rezerwacje-restauracja/app" },
  { id: "pos-hotelapp", sourcePath: "/home/ubuntu/Projects/pos-hotelapp" },
  { id: "rozliczenie-dnia", sourcePath: "/home/ubuntu/Projects/rozliczenie-dnia/app" },
  { id: "rozliczenie-dnia-oaza" },
  { id: "strefa-kelnera", sourcePath: "/home/ubuntu/Projects/strefa-kelnera-app" },
  { id: "recipebook", sourcePath: "/home/ubuntu/Projects/recipebook/app" },
  { id: "magazyn", sourcePath: "/home/ubuntu/Projects/magazyn/app" },
  {
    id: "zakupy",
    sourcePath: "/home/ubuntu/Projects/zakupy-app",
    enabled: false,
    visibleInHome: false,
  },
  {
    id: "haccp-panel",
    sourcePath: "/home/ubuntu/Projects/haccp-panel/app",
    enabled: false,
    visibleInHome: false,
  },
  { id: "fincost", sourcePath: "/home/ubuntu/Projects/FinCostApp/frontend" },
  { id: "przelewy", sourcePath: "/home/ubuntu/Projects/przelewy-app/app" },
  { id: "ksef", sourcePath: "/home/ubuntu/Projects/ksef-explorer/app" },
  { id: "beo-finanse", sourcePath: "/home/ubuntu/Projects/beo-finanse-app" },
  { id: "grello", sourcePath: "/home/ubuntu/Projects/grello/app" },
  { id: "marketingowiec", sourcePath: "/home/ubuntu/Projects/marketingowiec/app" },
  { id: "assets", sourcePath: "/home/ubuntu/Projects/assets/app" },
  { id: "chat", enabled: false, visibleInHome: false },
  {
    id: "metersapp",
    sourcePath: "/home/ubuntu/Projects/metersapp/app",
    enabled: false,
    visibleInHome: false,
  },
  { id: "elektryk", sourcePath: "/home/ubuntu/Projects/maintenance-workspace/products/elektryk/app" },
  { id: "tereny-zielone", sourcePath: "/home/ubuntu/Projects/tereny-zielone/app" },
];
